name: Documentation

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install --yes doxygen
      - name: Install documentation dependencies
        run: python -m pip install -e '.[docs]'
      - name: Configure documentation
        run: cmake -S docs -B build/docs
      - name: Build documentation
        run: cmake --build build/docs --target docs
      - name: Upload documentation site
        uses: actions/upload-artifact@v4
        with:
          name: documentation-site
          path: build/docs/html
